/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VideoRequest {
    creator: Principal;
    mainTopic: string;
    requirements: ContentRequest;
    videoTitle: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SeoPackResponse {
    titles: Array<string>;
    hashtags: Array<string>;
    tags: Array<string>;
    pinnedComment: string;
    description: string;
    chapters: Array<string>;
}
export interface ImageGenerationParams {
    model: string;
    guidanceScale: number;
    seed: bigint;
    steps: bigint;
    samplerMethod: string;
    imageBase64: string;
    prompt: string;
    negativePrompt: string;
}
export interface VoiceoverRequest {
    emotion: Emotion;
    script: string;
    language: Language;
    speed: VoiceSpeed;
    voiceGender: VoiceGender;
}
export interface VideoResponse {
    animationPlan: AnimationPlan;
    script: string;
    storyboard: Storyboard;
    exportPlan: ExportPlan;
    subtitles: Array<string>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SubtitleRequest {
    script: string;
    language: Language;
    style: SubtitleStyle;
}
export interface CoinPurchasePlan {
    id: bigint;
    coinAmount: bigint;
    name: string;
    stripePriceId?: string;
    currencyCode: string;
    price: string;
}
export interface Storyboard {
    scenes: Array<string>;
}
export interface AnimationPlan {
    steps: Array<string>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransactionRecord {
    principal: Principal;
    feature: string;
    transactionType: TransactionType;
    timestamp: bigint;
    balanceAfter: bigint;
    amount: bigint;
}
export interface SeoPackRequest {
    mainTopic: string;
    videoTitle: string;
}
export interface ExportPlan {
    outputDestination: string;
    animationPlan: AnimationPlan;
    script: string;
    compressionMethod: string;
    storyboard: Storyboard;
    exportFormat: string;
    qualityLevel: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface ContentRequest {
    includeSubtitles: boolean;
    createScript: boolean;
    voiceLanguage: Language;
    scriptLanguage: Language;
    autoTranslateSubtitles: boolean;
    subtitleLanguage: Language;
}
export interface ColdEmailResponse {
    finalOutput: string;
    subjectLines: Array<string>;
    mainEmail: string;
    followUp1: string;
    followUp2: string;
}
export interface Message {
    height?: bigint;
    content: string;
    role: ChatRole;
    timestamp: bigint;
    imageBytes?: Uint8Array;
    width?: bigint;
}
export interface ColdEmailRequest {
    personalization: string;
    subject: string;
    companySector: string;
    useCase: string;
    recipient: string;
    meetingRequest: string;
    targetCompany: string;
    productDetails: string;
}
export interface UserProfile {
    principal: Principal;
    displayName: string;
    avatar: string;
}
export enum ChatRole {
    user = "user",
    assistant = "assistant"
}
export enum Emotion {
    normal = "normal",
    energetic = "energetic",
    serious = "serious"
}
export enum Language {
    ar = "ar",
    de = "de",
    en = "en",
    es = "es",
    fr = "fr",
    hi = "hi",
    it = "it",
    ja = "ja",
    ko = "ko",
    pt = "pt",
    ru = "ru",
    zh = "zh"
}
export enum SubtitleStyle {
    mrbeastStyle = "mrbeastStyle",
    bold = "bold",
    simple = "simple"
}
export enum TransactionType {
    credit = "credit",
    featureUsage = "featureUsage",
    debit = "debit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VoiceGender {
    female = "female",
    male = "male"
}
export enum VoiceSpeed {
    normal = "normal",
    fast = "fast",
    slow = "slow"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminAddCoins(user: Principal, coins: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    chargeFeatureUsage(featureName: string): Promise<void>;
    clearChatHistory(): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    generateColdEmail(request: ColdEmailRequest): Promise<ColdEmailResponse>;
    generateSeoPack(request: SeoPackRequest): Promise<SeoPackResponse>;
    generateSubtitles(request: SubtitleRequest): Promise<string>;
    generateVideoResponse(request: VideoRequest): Promise<VideoResponse>;
    generateVoiceover(request: VoiceoverRequest): Promise<string>;
    getAllChatHistories(): Promise<Array<[Principal, Array<Message>]>>;
    getAllImageGenerationParams(): Promise<Array<[Principal, Array<ImageGenerationParams>]>>;
    getAppInfo(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatHistory(): Promise<Array<Message> | null>;
    getCoinBalance(): Promise<bigint>;
    getCurrentTime(): Promise<bigint>;
    getImageGenerationParams(user: Principal): Promise<Array<ImageGenerationParams> | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTransactionHistory(): Promise<Array<TransactionRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listCoinPurchasePlans(): Promise<Array<CoinPurchasePlan>>;
    processChatMessage(userMessage: Message): Promise<Array<Message>>;
    purchaseCoins(planId: bigint): Promise<bigint>;
    purchaseCoinsWithStripe(stripeSessionId: string, planId: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitImageGenerationParams(params: ImageGenerationParams): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ChatRole as _ChatRole, CoinPurchasePlan as _CoinPurchasePlan, ContentRequest as _ContentRequest, Emotion as _Emotion, ImageGenerationParams as _ImageGenerationParams, Language as _Language, Message as _Message, StripeSessionStatus as _StripeSessionStatus, SubtitleRequest as _SubtitleRequest, SubtitleStyle as _SubtitleStyle, TransactionRecord as _TransactionRecord, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, VideoRequest as _VideoRequest, VoiceGender as _VoiceGender, VoiceSpeed as _VoiceSpeed, VoiceoverRequest as _VoiceoverRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminAddCoins(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddCoins(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddCoins(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async chargeFeatureUsage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.chargeFeatureUsage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chargeFeatureUsage(arg0);
            return result;
        }
    }
    async clearChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async generateColdEmail(arg0: ColdEmailRequest): Promise<ColdEmailResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.generateColdEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateColdEmail(arg0);
            return result;
        }
    }
    async generateSeoPack(arg0: SeoPackRequest): Promise<SeoPackResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSeoPack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSeoPack(arg0);
            return result;
        }
    }
    async generateSubtitles(arg0: SubtitleRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSubtitles(to_candid_SubtitleRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSubtitles(to_candid_SubtitleRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateVideoResponse(arg0: VideoRequest): Promise<VideoResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.generateVideoResponse(to_candid_VideoRequest_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateVideoResponse(to_candid_VideoRequest_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateVoiceover(arg0: VoiceoverRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateVoiceover(to_candid_VoiceoverRequest_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateVoiceover(to_candid_VoiceoverRequest_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllChatHistories(): Promise<Array<[Principal, Array<Message>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChatHistories();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChatHistories();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllImageGenerationParams(): Promise<Array<[Principal, Array<ImageGenerationParams>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImageGenerationParams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImageGenerationParams();
            return result;
        }
    }
    async getAppInfo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppInfo();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(): Promise<Array<Message> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoinBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinBalance();
            return result;
        }
    }
    async getCurrentTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTime();
            return result;
        }
    }
    async getImageGenerationParams(arg0: Principal): Promise<Array<ImageGenerationParams> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImageGenerationParams(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImageGenerationParams(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listCoinPurchasePlans(): Promise<Array<CoinPurchasePlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoinPurchasePlans();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoinPurchasePlans();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async processChatMessage(arg0: Message): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.processChatMessage(to_candid_Message_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processChatMessage(to_candid_Message_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseCoins(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseCoins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseCoins(arg0);
            return result;
        }
    }
    async purchaseCoinsWithStripe(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseCoinsWithStripe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseCoinsWithStripe(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitImageGenerationParams(arg0: ImageGenerationParams): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitImageGenerationParams(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitImageGenerationParams(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ChatRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatRole): ChatRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_CoinPurchasePlan_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoinPurchasePlan): CoinPurchasePlan {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionRecord_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionRecord): TransactionRecord {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Message>]): Array<Message> | null {
    return value.length === 0 ? null : from_candid_vec_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ImageGenerationParams>]): Array<ImageGenerationParams> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    height: [] | [bigint];
    content: string;
    role: _ChatRole;
    timestamp: bigint;
    imageBytes: [] | [Uint8Array];
    width: [] | [bigint];
}): {
    height?: bigint;
    content: string;
    role: ChatRole;
    timestamp: bigint;
    imageBytes?: Uint8Array;
    width?: bigint;
} {
    return {
        height: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.height)),
        content: value.content,
        role: from_candid_ChatRole_n27(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp,
        imageBytes: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.imageBytes)),
        width: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.width))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    feature: string;
    transactionType: _TransactionType;
    timestamp: bigint;
    balanceAfter: bigint;
    amount: bigint;
}): {
    principal: Principal;
    feature: string;
    transactionType: TransactionType;
    timestamp: bigint;
    balanceAfter: bigint;
    amount: bigint;
} {
    return {
        principal: value.principal,
        feature: value.feature,
        transactionType: from_candid_TransactionType_n42(_uploadFile, _downloadFile, value.transactionType),
        timestamp: value.timestamp,
        balanceAfter: value.balanceAfter,
        amount: value.amount
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    coinAmount: bigint;
    name: string;
    stripePriceId: [] | [string];
    currencyCode: string;
    price: string;
}): {
    id: bigint;
    coinAmount: bigint;
    name: string;
    stripePriceId?: string;
    currencyCode: string;
    price: string;
} {
    return {
        id: value.id,
        coinAmount: value.coinAmount,
        name: value.name,
        stripePriceId: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.stripePriceId)),
        currencyCode: value.currencyCode,
        price: value.price
    };
}
function from_candid_tuple_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_Message>]): [Principal, Array<Message>] {
    return [
        value[0],
        from_candid_vec_n23(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): ChatRole {
    return "user" in value ? ChatRole.user : "assistant" in value ? ChatRole.assistant : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n37(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    featureUsage: null;
} | {
    debit: null;
}): TransactionType {
    return "credit" in value ? TransactionType.credit : "featureUsage" in value ? TransactionType.featureUsage : "debit" in value ? TransactionType.debit : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_Message>]>): Array<[Principal, Array<Message>]> {
    return value.map((x)=>from_candid_tuple_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionRecord>): Array<TransactionRecord> {
    return value.map((x)=>from_candid_TransactionRecord_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoinPurchasePlan>): Array<CoinPurchasePlan> {
    return value.map((x)=>from_candid_CoinPurchasePlan_n45(_uploadFile, _downloadFile, x));
}
function to_candid_ChatRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRole): _ChatRole {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_ContentRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentRequest): _ContentRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Emotion_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Emotion): _Emotion {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Message_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): _Message {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_SubtitleRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubtitleRequest): _SubtitleRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SubtitleStyle_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubtitleStyle): _SubtitleStyle {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VideoRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoRequest): _VideoRequest {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_VoiceGender_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceGender): _VoiceGender {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_VoiceSpeed_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceSpeed): _VoiceSpeed {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_VoiceoverRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceoverRequest): _VoiceoverRequest {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: Principal;
    mainTopic: string;
    requirements: ContentRequest;
    videoTitle: string;
}): {
    creator: Principal;
    mainTopic: string;
    requirements: _ContentRequest;
    videoTitle: string;
} {
    return {
        creator: value.creator,
        mainTopic: value.mainTopic,
        requirements: to_candid_ContentRequest_n11(_uploadFile, _downloadFile, value.requirements),
        videoTitle: value.videoTitle
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    includeSubtitles: boolean;
    createScript: boolean;
    voiceLanguage: Language;
    scriptLanguage: Language;
    autoTranslateSubtitles: boolean;
    subtitleLanguage: Language;
}): {
    includeSubtitles: boolean;
    createScript: boolean;
    voiceLanguage: _Language;
    scriptLanguage: _Language;
    autoTranslateSubtitles: boolean;
    subtitleLanguage: _Language;
} {
    return {
        includeSubtitles: value.includeSubtitles,
        createScript: value.createScript,
        voiceLanguage: to_candid_Language_n5(_uploadFile, _downloadFile, value.voiceLanguage),
        scriptLanguage: to_candid_Language_n5(_uploadFile, _downloadFile, value.scriptLanguage),
        autoTranslateSubtitles: value.autoTranslateSubtitles,
        subtitleLanguage: to_candid_Language_n5(_uploadFile, _downloadFile, value.subtitleLanguage)
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emotion: Emotion;
    script: string;
    language: Language;
    speed: VoiceSpeed;
    voiceGender: VoiceGender;
}): {
    emotion: _Emotion;
    script: string;
    language: _Language;
    speed: _VoiceSpeed;
    voiceGender: _VoiceGender;
} {
    return {
        emotion: to_candid_Emotion_n15(_uploadFile, _downloadFile, value.emotion),
        script: value.script,
        language: to_candid_Language_n5(_uploadFile, _downloadFile, value.language),
        speed: to_candid_VoiceSpeed_n17(_uploadFile, _downloadFile, value.speed),
        voiceGender: to_candid_VoiceGender_n19(_uploadFile, _downloadFile, value.voiceGender)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    script: string;
    language: Language;
    style: SubtitleStyle;
}): {
    script: string;
    language: _Language;
    style: _SubtitleStyle;
} {
    return {
        script: value.script,
        language: to_candid_Language_n5(_uploadFile, _downloadFile, value.language),
        style: to_candid_SubtitleStyle_n7(_uploadFile, _downloadFile, value.style)
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    height?: bigint;
    content: string;
    role: ChatRole;
    timestamp: bigint;
    imageBytes?: Uint8Array;
    width?: bigint;
}): {
    height: [] | [bigint];
    content: string;
    role: _ChatRole;
    timestamp: bigint;
    imageBytes: [] | [Uint8Array];
    width: [] | [bigint];
} {
    return {
        height: value.height ? candid_some(value.height) : candid_none(),
        content: value.content,
        role: to_candid_ChatRole_n49(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp,
        imageBytes: value.imageBytes ? candid_some(value.imageBytes) : candid_none(),
        width: value.width ? candid_some(value.width) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Emotion): {
    normal: null;
} | {
    energetic: null;
} | {
    serious: null;
} {
    return value == Emotion.normal ? {
        normal: null
    } : value == Emotion.energetic ? {
        energetic: null
    } : value == Emotion.serious ? {
        serious: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceSpeed): {
    normal: null;
} | {
    fast: null;
} | {
    slow: null;
} {
    return value == VoiceSpeed.normal ? {
        normal: null
    } : value == VoiceSpeed.fast ? {
        fast: null
    } : value == VoiceSpeed.slow ? {
        slow: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceGender): {
    female: null;
} | {
    male: null;
} {
    return value == VoiceGender.female ? {
        female: null
    } : value == VoiceGender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRole): {
    user: null;
} | {
    assistant: null;
} {
    return value == ChatRole.user ? {
        user: null
    } : value == ChatRole.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    ar: null;
} | {
    de: null;
} | {
    en: null;
} | {
    es: null;
} | {
    fr: null;
} | {
    hi: null;
} | {
    it: null;
} | {
    ja: null;
} | {
    ko: null;
} | {
    pt: null;
} | {
    ru: null;
} | {
    zh: null;
} {
    return value == Language.ar ? {
        ar: null
    } : value == Language.de ? {
        de: null
    } : value == Language.en ? {
        en: null
    } : value == Language.es ? {
        es: null
    } : value == Language.fr ? {
        fr: null
    } : value == Language.hi ? {
        hi: null
    } : value == Language.it ? {
        it: null
    } : value == Language.ja ? {
        ja: null
    } : value == Language.ko ? {
        ko: null
    } : value == Language.pt ? {
        pt: null
    } : value == Language.ru ? {
        ru: null
    } : value == Language.zh ? {
        zh: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubtitleStyle): {
    mrbeastStyle: null;
} | {
    bold: null;
} | {
    simple: null;
} {
    return value == SubtitleStyle.mrbeastStyle ? {
        mrbeastStyle: null
    } : value == SubtitleStyle.bold ? {
        bold: null
    } : value == SubtitleStyle.simple ? {
        simple: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
