/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnimationPlan { 'steps' : Array<string> }
export type ChatRole = { 'user' : null } |
  { 'assistant' : null };
export interface CoinPurchasePlan {
  'id' : bigint,
  'coinAmount' : bigint,
  'name' : string,
  'stripePriceId' : [] | [string],
  'currencyCode' : string,
  'price' : string,
}
export interface ColdEmailRequest {
  'personalization' : string,
  'subject' : string,
  'companySector' : string,
  'useCase' : string,
  'recipient' : string,
  'meetingRequest' : string,
  'targetCompany' : string,
  'productDetails' : string,
}
export interface ColdEmailResponse {
  'finalOutput' : string,
  'subjectLines' : Array<string>,
  'mainEmail' : string,
  'followUp1' : string,
  'followUp2' : string,
}
export interface ContentRequest {
  'includeSubtitles' : boolean,
  'createScript' : boolean,
  'voiceLanguage' : Language,
  'scriptLanguage' : Language,
  'autoTranslateSubtitles' : boolean,
  'subtitleLanguage' : Language,
}
export type Emotion = { 'normal' : null } |
  { 'energetic' : null } |
  { 'serious' : null };
export interface ExportPlan {
  'outputDestination' : string,
  'animationPlan' : AnimationPlan,
  'script' : string,
  'compressionMethod' : string,
  'storyboard' : Storyboard,
  'exportFormat' : string,
  'qualityLevel' : string,
}
export interface ImageGenerationParams {
  'model' : string,
  'guidanceScale' : number,
  'seed' : bigint,
  'steps' : bigint,
  'samplerMethod' : string,
  'imageBase64' : string,
  'prompt' : string,
  'negativePrompt' : string,
}
export type Language = { 'ar' : null } |
  { 'de' : null } |
  { 'en' : null } |
  { 'es' : null } |
  { 'fr' : null } |
  { 'hi' : null } |
  { 'it' : null } |
  { 'ja' : null } |
  { 'ko' : null } |
  { 'pt' : null } |
  { 'ru' : null } |
  { 'zh' : null };
export interface Message {
  'height' : [] | [bigint],
  'content' : string,
  'role' : ChatRole,
  'timestamp' : bigint,
  'imageBytes' : [] | [Uint8Array],
  'width' : [] | [bigint],
}
export interface SeoPackRequest { 'mainTopic' : string, 'videoTitle' : string }
export interface SeoPackResponse {
  'titles' : Array<string>,
  'hashtags' : Array<string>,
  'tags' : Array<string>,
  'pinnedComment' : string,
  'description' : string,
  'chapters' : Array<string>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Storyboard { 'scenes' : Array<string> }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubtitleRequest {
  'script' : string,
  'language' : Language,
  'style' : SubtitleStyle,
}
export type SubtitleStyle = { 'mrbeastStyle' : null } |
  { 'bold' : null } |
  { 'simple' : null };
export interface TransactionRecord {
  'principal' : Principal,
  'feature' : string,
  'transactionType' : TransactionType,
  'timestamp' : bigint,
  'balanceAfter' : bigint,
  'amount' : bigint,
}
export type TransactionType = { 'credit' : null } |
  { 'featureUsage' : null } |
  { 'debit' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'avatar' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoRequest {
  'creator' : Principal,
  'mainTopic' : string,
  'requirements' : ContentRequest,
  'videoTitle' : string,
}
export interface VideoResponse {
  'animationPlan' : AnimationPlan,
  'script' : string,
  'storyboard' : Storyboard,
  'exportPlan' : ExportPlan,
  'subtitles' : Array<string>,
}
export type VoiceGender = { 'female' : null } |
  { 'male' : null };
export type VoiceSpeed = { 'normal' : null } |
  { 'fast' : null } |
  { 'slow' : null };
export interface VoiceoverRequest {
  'emotion' : Emotion,
  'script' : string,
  'language' : Language,
  'speed' : VoiceSpeed,
  'voiceGender' : VoiceGender,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminAddCoins' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chargeFeatureUsage' : ActorMethod<[string], undefined>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'generateColdEmail' : ActorMethod<[ColdEmailRequest], ColdEmailResponse>,
  'generateSeoPack' : ActorMethod<[SeoPackRequest], SeoPackResponse>,
  'generateSubtitles' : ActorMethod<[SubtitleRequest], string>,
  'generateVideoResponse' : ActorMethod<[VideoRequest], VideoResponse>,
  'generateVoiceover' : ActorMethod<[VoiceoverRequest], string>,
  'getAllChatHistories' : ActorMethod<[], Array<[Principal, Array<Message>]>>,
  'getAllImageGenerationParams' : ActorMethod<
    [],
    Array<[Principal, Array<ImageGenerationParams>]>
  >,
  'getAppInfo' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], [] | [Array<Message>]>,
  'getCoinBalance' : ActorMethod<[], bigint>,
  'getCurrentTime' : ActorMethod<[], bigint>,
  'getImageGenerationParams' : ActorMethod<
    [Principal],
    [] | [Array<ImageGenerationParams>]
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransactionHistory' : ActorMethod<[], Array<TransactionRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listCoinPurchasePlans' : ActorMethod<[], Array<CoinPurchasePlan>>,
  'processChatMessage' : ActorMethod<[Message], Array<Message>>,
  'purchaseCoins' : ActorMethod<[bigint], bigint>,
  'purchaseCoinsWithStripe' : ActorMethod<[string, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitImageGenerationParams' : ActorMethod<
    [ImageGenerationParams],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];